[package]
name = "magelogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.0.0"
colored = "2"
getopts = "0.2.17"